name: dev-build

#this drops to github with beta tag?

on:
  push:
    branches: [ dev]
  pull_request:
    branches: [ dev, main ]

  workflow_dispatch:

jobs:
  build:
    name: Build Comet-Nuget
    env:
        NUPKG_MAJOR: 0.2
        BASE: 335
    runs-on: windows-2022

    steps: 
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name:  install .NET 
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
          & .\dotnet-install.ps1 -Quality daily -Channel 6.0.2xx -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
          & dotnet --list-sdks    
              
      # - name: Install Visual Studio Preview
      #   shell: pwsh
      #   run: powershell .\build\install-vs.ps1
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
        
      # - name: Add MSBuild to Path
      #   shell: pwsh
      #   run: |
      #     dotnet tool update -g dotnet-vs
      #     & echo "$(vs where preview --prop=InstallationPath)\MSBuild\Current\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: Install Maui Workload
        shell: pwsh
        run: |
          & dotnet workload install android ios maccatalyst tvos macos maui wasm-tools `
            --from-rollback-file https://aka.ms/dotnet/maui/preview.14.json  `
            --source https://aka.ms/dotnet6/nuget/index.json `
            --source https://pkgs.dev.azure.com/dnceng/public/_packaging/-shipping-2/nuget/v3/index.json `
            --source https://pkgs.dev.azure.com/xamarin/public/_packaging/maui-net6-shipping/nuget/v3/index.json `
            --source https://api.nuget.org/v3/index.json `
            --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-6dd808ff-1/nuget/v3/index.json `
            --source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-ee0a97a0/nuget/v3/index.json


      - name: Set Maui Version
        run: dotnet run --project build/MauiVersionUpdater/MauiVersionUpdater.csproj -- https://aka.ms/dotnet/maui/main.json

      - name: Restore Comet-net6-Nuget.sln
        run: msbuild /r build/Comet-net6-Nuget.sln
 
      - name: Build Comet-net6-Nuget.sln
        run: MSBuild build/Comet-net6-Nuget.sln
        
      - name: Nuget Pack step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=0.3.$MINOR_VERSION-alpha
          echo "PACKAGE VERSION: $VERSION"
          nuget pack Comet.nuspec -version $VERSION -Symbols -SymbolPackageFormat snupkg

      - name: Nuget Pack Template step
        shell: bash
        run: |
          MINOR_VERSION=$(( $BASE + $GITHUB_RUN_NUMBER ))
          VERSION=0.3.$MINOR_VERSION-alpha
          echo "PACKAGE VERSION: $VERSION"
          nuget pack "templates\comet-templates.nuspec" -version $VERSION
                    
      - uses: actions/upload-artifact@v2
        name: Upload Nuget Artifact
        with:
          name: nuget-artifact.${{env.GITHUB_RUN_NUMBER}}
          path: |
            **\*.nupkg
            **\*.snupkg
            **\*.symbols.nupkg

      # - name: Restore Comet-Tests.sln
      #   run: nuget restore build/Comet-Tests.sln

      # - name: Build Tests Project
      #   run: msbuild tests/Comet.Tests/Comet.Tests.csproj /p:Configuration=Release
        
      # - name: Run Tests Project
      #   run: dotnet test tests/Comet.Tests/Comet.Tests.csproj
      
